#!/bin/bash
# imprime todas las ocurrencias de $1 en los archivos
# en el directorio actual con extensión .c o .h
# shellscript1
if [ $# -ne 1 ]; then
	echo "uso: shellscript1 <patron> | -h"
	exit 1
fi
if [ $1 = "-h" ]; then
	echo "Texto explicativo."
	exit 0
fi
PATRON=$1
for i in `find ./ -name “*.[hc]”`
do
	cantidad=grep -c $PATRON $i
	if [ $cantidad -ne 0 ]; then
		echo "--------------"
		echo $i
		grep $PATRON $i
	fi
done