#!/bin/bash
if [ $# -lt 3 ] ; then
	echo "Command Usage: reemplazar <cadena_original> <cadena_nueva> <archivo>"
fi
cadena_original=$1
shift
cadena_nueva=$1
shift
for i in $@;
do
	archivo=$1
	#hacemos el sed pero lo guardamos en un archivo temporal
	sed {s/$cadena_original/$cadena_nueva/g} $archivo > $archivo.t
	#luego lo renombramos y nos quedamos con el original, pero cambiado
	mv $archivo.t $archivo
	shift
done

